# Generated by Django 5.0.4 on 2025-12-27 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('rowid', models.BigIntegerField(db_column='rowid', primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_column='symbol', max_length=64)),
                ('yahoo_symbol', models.CharField(db_column='yahoo_symbol', max_length=64)),
                ('ts_readable', models.CharField(blank=True, db_column='ts_readable', max_length=64, null=True)),
                ('open', models.FloatField(blank=True, db_column='open', null=True)),
                ('high', models.FloatField(blank=True, db_column='high', null=True)),
                ('low', models.FloatField(blank=True, db_column='low', null=True)),
                ('close', models.FloatField(blank=True, db_column='close', null=True)),
                ('adj_close', models.FloatField(blank=True, db_column='adj_close', null=True)),
                ('volume', models.FloatField(blank=True, db_column='volume', null=True)),
                ('liquidity', models.FloatField(blank=True, db_column='liquidity', null=True)),
            ],
            options={
                'db_table': 'prices',
                'ordering': ['-ts_readable'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportedCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
